feat: los and eurovoc rdf endpoints
Informasjonsforvaltning/fdk-reference-data pull request #130
Opened 2023-03-13 07:15 UTC by NilsOveTen

2023-03-13 14:31 UTC, jeffreiffers requested changes

2023-03-13 14:31 UTC, jeffreiffers commented on src/main/java/no/fdk/referencedata/los/LosController.java
> +    @GetMapping(path = "rdf")
```suggestion
    @GetMapping(produces = "text/turtle")
```

2023-03-13 14:31 UTC, jeffreiffers commented on src/main/java/no/fdk/referencedata/los/LosController.java
> +    @GetMapping(path = "rdf")
Samme gelder alle andre endepunkter.

2023-03-14 07:25 UTC, NilsOveTen commented on src/main/java/no/fdk/referencedata/los/LosController.java
> +    @GetMapping(path = "rdf")
c54049d

2023-03-14 14:04 UTC, pooriamehregan approved these changes

2023-03-15 11:23 UTC, jeffreiffers approved these changes

2023-03-16 06:47 UTC, merged