Feat/jr/new reference data
Informasjonsforvaltning/fdk-reference-data pull request #50
Opened 2021-05-20 10:27 UTC by jeffreiffers

2021-05-28 10:07 UTC, azaxarov requested changes

2021-05-28 10:07 UTC, azaxarov commented on src/main/java/no/fdk/referencedata/mediatype/iana/IANAMediaTypeHarvester.java
> +    }
```suggestion
    private Flux<String> extractMediaTypeRegistryRecords(URL url) {
        try {
            CSVFormat format = CSVFormat.DEFAULT
                .withFirstRecordAsHeader()
                .withSkipHeaderRecord();
            Charset charset = Charset.defaultCharset();

            List<CSVRecord> records = CSVParser.parse(url, charset, format).getRecords();

            return Flux.fromIterable(records)
                .map(record -> record.get(0))
                .map(String::trim)
                .filter(Predicate.not(String::isEmpty));
        } catch (IOException e) {
            log.error("Failed to extract media type registry records from: {}", url.toString(), e);
        }
```

2021-05-28 10:07 UTC, azaxarov commented on src/main/java/no/fdk/referencedata/mediatype/iana/IANAMediaTypeHarvester.java
> +    public Flux<Resource> getMediaTypesSources()  {
Bruk av resource her er unødvendig. Se https://github.com/Informasjonsforvaltning/fdk-metadata-quality-service/blob/master/src/main/java/no/fdk/service/IANAMediaTypeService.java

2021-05-28 10:07 UTC, azaxarov commented on src/main/java/no/fdk/referencedata/filetype/eu/EUFileTypeHarvester.java
> +}
```suggestion
}

```

2021-05-28 10:07 UTC, azaxarov commented on src/main/java/no/fdk/referencedata/filetype/eu/EUFileTypeHarvester.java
> +        }
Ekstraher ut i egen metode og bruk deretter Mono.justOrEmpty for å håndtere null verdi

2021-05-28 10:07 UTC, azaxarov commented on src/main/java/no/fdk/referencedata/filetype/eu/EUFileTypeHarvester.java
> +            final RestTemplate restTemplate = new RestTemplate();
Kan bruke reactive client her i stedet for rest template

2021-05-28 10:07 UTC, azaxarov commented on src/main/java/no/fdk/referencedata/filetype/eu/EUFileTypeHarvester.java
> +                .blockFirst();
Prøv å unngå blokkerende operasjoner

2021-05-31 08:51 UTC, jeffreiffers commented on lombok.config
> +lombok.anyConstructor.addConstructorProperties=true
Den sørger for at Jackson klarer å serialisere data objektene.

2021-05-31 08:51 UTC, jeffreiffers commented on pom.xml
> +            <version>3.6.0</version>
Nei den skal vekk

2021-05-31 08:51 UTC, jeffreiffers commented on pom.xml
> +            <version>2.9.2</version>
Ja

2021-05-31 08:52 UTC, jeffreiffers commented on src/main/java/no/fdk/referencedata/mediatype/iana/IANAMediaTypeHarvester.java
> +    public Flux<Resource> getMediaTypesSources()  {
Brukes sånn at vi kan teste klassen.

2021-06-07 06:02 UTC, NilsOveTen reviewed
Noice! Men er enig i mesteparten fra Alex

2021-08-09 10:43 UTC, merged